name: Kafka Publish

on: [push, pull_request, create, issue_comment, delete]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Start Bitname Kafka
      uses: bbcCorp/kafka-actions@v1
